<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; }
        .container { max-width: 600px; margin: 20px auto; padding: 20px; border: 1px solid #eee; border-radius: 8px; }
        .header { text-align: center; border-bottom: 2px solid #f4f4f4; padding-bottom: 20px; margin-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #d97706; text-transform: uppercase; letter-spacing: 1px; }
        .summary { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .summary-box { flex: 1; padding: 15px; background: #f9f9f9; border-radius: 6px; text-align: center; margin: 0 5px; }
        .summary-label { font-size: 10px; text-transform: uppercase; color: #666; font-weight: bold; margin-bottom: 5px; }
        .summary-value { font-size: 18px; font-weight: bold; }
        .text-danger { color: #dc2626; }
        .text-success { color: #16a34a; }
        .table { w-full border-collapse: collapse; margin-top: 20px; width: 100%; }
        .table th { background: #f4f4f4; padding: 10px; text-align: left; font-size: 12px; border-bottom: 1px solid #ddd; }
        .table td { padding: 10px; font-size: 12px; border-bottom: 1px solid #eee; }
        .footer { margin-top: 30px; text-align: center; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
        .message { background: #fffbeb; border-left: 4px solid #f59e0b; padding: 15px; margin-bottom: 20px; font-style: italic; font-size: 13px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">PropMaster</div>
            <h2 style="margin-top: 10px; color: #444;">Account Statement</h2>
            <p style="font-size: 14px; color: #777;">{{ $record->tenant->name }} | {{ $record->property->name }}</p>
        </div>

        @if($customMessage)
            <div class="message">
                "{{ $customMessage }}"
            </div>
        @endif

        <div class="summary">
            <div class="summary-box">
                <div class="summary-label">Total Charges</div>
                <div class="summary-value">RM {{ number_format($totalCharges, 2) }}</div>
            </div>
            <div class="summary-box">
                <div class="summary-label">Total Paid</div>
                <div class="summary-value">RM {{ number_format($totalPaid, 2) }}</div>
            </div>
            <div class="summary-box">
                <div class="summary-label">Outstanding Balance</div>
                <div class="summary-value @if($balance > 0) text-danger @elseif($balance < 0) text-success @endif">
                    RM {{ number_format(abs($balance), 2) }}
                    @if($balance < 0) (CR) @endif
                </div>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th style="text-align: right;">Debit</th>
                    <th style="text-align: right;">Credit</th>
                </tr>
            </thead>
            <tbody>
                @foreach($transactions as $tx)
                    <tr>
                        <td>{{ $tx['date']->format('d M Y') }}</td>
                        <td>{{ $tx['description'] }}</td>
                        <td style="text-align: right; color: #dc2626;">{{ $tx['debit'] > 0 ? number_format($tx['debit'], 2) : '-' }}</td>
                        <td style="text-align: right; color: #16a34a;">{{ $tx['credit'] > 0 ? number_format($tx['credit'], 2) : '-' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            <p>This is an automated account statement generated by PropMaster.</p>
            <p>If you have any questions regarding your statement, please contact us.</p>
            <p>&copy; {{ date('Y') }} PropMaster Management</p>
        </div>
    </div>
</body>
</html>
